name: Dependabot

on:
 push:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Dependabot
        run: |
          docker run --rm -v $PWD:/mnt:delegated -w /mnt \
          -e "DEPENDABOT_CONFIG=.github/dependabot.yml" \
          dependabot/dependabot-core:latest
    

      
        
