name: Add PR Owner

on:
  pull_request:
    types:
    - labeled
    
jobs:
  angular-test-coverage:
    runs-on: ubuntu-latest
    name: angular test coverage update
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Jasmine tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Coverage report
        uses: eleboys/test-coverage-report-action@v1.0.2
        id: report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-summary.json
          title: Karma Test Coverage

      - name: Print the output summary
        run: echo "Report coverage json ${{ steps.report.outputs.summary }}"
