name: PR Labeler
on:
  pull_request:
    types: 
     - labeled

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: nrccua-walter-manger/pr-label-by-base@v0.1-alpha
        with:
          configuration-path: .github/pr-label-by-base.yml
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
