on:
  schedule:
  - cron:  '*/2 * * * *'
 
 
name: Issue opened
jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Release
          COLUMN: Todo
