name: pr-labeler

on: [pull_request]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: coverwallet/pr-labeler@v1.2.1
        with:
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          exclude_files: '.txt'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
