on:
  workflow_dispatch:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v3
      - run: npn npm@5
      - run: npm ci
      - run: npm run licensed-check
