on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: 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
          project-name: Release
          column-name: In Progress
