on:
  issues:
    types: [opened]
name: Issue opened
jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: https://github.com/users/cledsonAlves/projects/3
          COLUMN: In Progress
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
