name: Add Card Project
env:
   RELEASE_BOOT_TOKEN: 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
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: ${{ env.RELEASE_BOOT_TOKEN }}
          project-location: https://github.com/users/cledsonAlves/projects/3
          project-name: Release
          column-name: In Progress
