name: Valida Pull Request
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  opened:
    if: github.event.review.state == 'opened'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
