on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: ${{ secrets.SECRET_ACTION }}
          project-name: Release
          project-location: https://github.com/users/cledsonAlves/projects/3
          project-number: 3
          column-name: In Progress
          
 
