name: Call a reusable workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  call-workflow:
    uses: cledsonAlves/desafioandroidcledsonalves/.github/workflows/workflow-board.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: cledsonAlves/desafioandroidcledsonalves/.github/workflows/workflow-board.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

