name: Reusable workflow with matrix strategy

on:
  pull_request:
     types:
      - labeled


jobs:
  valida-label:
    uses: ./.github/workflows/validate_label.yml
    
    
  remove-label:
   runs-on: ubuntu-latest
   
   needs: valida-label
   steps:
    - run: echo  'Rodou todos os jobs'

  

    
    
