name: Reusable workflow with matrix strategy

on:
  pull_request:
     types:
      - labeled


jobs:
  call-workflow:
    uses: ./.github/workflows/validate_label.yml

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/validate_label.yml

    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    
