name: Reusable workflow with matrix strategy

on:
  pull_request:
     types:
      - labeled


jobs:
  call-workflow:
    uses: ./.github/workflows/validate_label.yml
    
  call-workflow-1-in-local-repo:
    uses: ./.github/workflows/validate_label.yml
    
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/validate_label.yml
    
  call-workflow-in-another-repo:
   runs-on: ubuntu-latest
   
   needs: call-workflow-2-in-local-repo
   steps:
    - run: echo  'Rodou todos os jobs'

  

    
    
