name: Boot CI

on:
  pull_request:
     types:
      - labeled


jobs:
  valida-label:
    uses: ./.github/workflows/validate_label.yml
    
    
  remove-label:
   uses: ./.github/workflows/validate_label.yml
   needs: valida-label

    
  remove-label2:
   uses: ./.github/workflows/validate_label.yml
   needs: remove-label
 

    
  

  

    
    
