name: Reusable workflow with matrix strategy

on:
  push:

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ./.github/workflows/reuse.yml
    with:
      target: ${{ matrix.target }}
