name: Boot CI

on:
  pull_request:
     types:
      - labeled

jobs:
  validate-label:
   if: github.event.label.name == 'merge_ready'
   runs-on: ubuntu-latest
   steps:
      - run: echo 'The label was merge_ready'
   
    
  removed-label:
    needs: validate-label
    if: >-
      github.event.pull_request.user.login != 'octobot' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: "Comment about changes we can't accept"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
         
        run: |
          gh pr edit $PR --remove-label 'merge_ready'
          gh pr edit $PR --add-label 'Sala de Integração'
          gh pr comment $PR --body 'Você não pode incluir a label Merge_Ready no seu PR, se o seu pr esta pronto para ser mergeado, por favor solicite a Sala de Integração!'
   
    
    

 

    
  

  

    
    
