name: Validate Label
on:
   workflow_call:
  

jobs:
  run_if_label_matches:
    if: github.event.label.name == 'merge_ready'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was bug'
